name : Gh - Pages
on :
 push :
    branches : [ master ]
jobs :
 build :
    runs - on : ubuntu - latest
    steps :
      - uses : actions / checkout @ v2 # Only works with v2
        uses : subosito / flutter - action @ vi
        uses : bluefireteam / flutter - gh - pages @ v